apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.1.4
    chart: minio
    helm:
      parameters:
        - name: mode
          value: 'distributed'
        - name: statefulset.replicaCount
          value: '1'
        - name: accessKey.password
          value: 'aaaaaaaaaa'
        - name: secretKey.password
          value: 'aaaaaaaaaa' 
        - name: defaultBuckets
          value: data-lake-bucket,data-lake-log-bucket
        - name: persistence.size
          value: '8Gi'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
