apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.9.6
    chart: postgresql
    helm:
      parameters:
        - name: postgresqlUsername
          value: 'postgres'
        - name: existingSecret
          value: 'data-lake'
        - name: persistence.size
          value: '1Gi'
        - name: initdbScripts.init\.sh
          value: |
            #!/bin/bash
            
              # Create readonly user and grant privileges              
              echo "Creating database"
              echo "CREATE DATABASE metastore_db;" | postgresql_execute "" "\$\POSTGRES_USER" "\$\POSTGRES_PASSWORD"
              echo "CREATE DATABASE superset;" | postgresql_execute "" "\$\POSTGRES_USER" "\$\POSTGRES_PASSWORD"
        - name: initdbScriptsSecret
          value: data-lake
        - name: initdbUser
          value: postgres
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
