apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.9.6
    chart: postgresql
    helm:
      parameters:
        - name: postgresqlUsername
          value: 'postgres'
        - name: existingSecret
          value: 'data-lake'
        - name: persistence.size
          value: '1Gi'
        - name: initdbScripts
          value: "init.sh: |\n
                #!/bin/bash\ninitDatabase() {\n
                "#!/bin/bash\ninitDatabase() {\n  echo \"Creating database for datalake\"    \n  echo \"CREATE DATABASE superset;\" | postgresql_execute
                \"\" \"$POSTGRES_USER\" \"$POSTGRES_PASSWORD\"\n  echo \"CREATE DATABASE metastore_db;\" | postgresql_execute \"\" \"$POSTGRES_USER\" \"$POSTGRES_PASSWORD\"\n}
            \      \ninitDatabase\n"
        - name: initdbScriptsSecret
          value: data-lake
        - name: initdbUser
          value: postgres
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
