apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-thrift-server
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://jackiefong.github.io/helm-charts'
    targetRevision: 1.0.0
    chart: spark-thrift-server
    helm:
      parameters:
        - name: driver.imagePullSecrets[0].name
          value: jackieregistry
        - name: driver.image.tag
          value: "3.1.2.2021.09.27.1731"
        - name: customconfig
          value: |
            - --conf
            - spark.kubernetes.container.image.pullSecrets=jackieregistry
  project: operation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
