apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.1.1
    chart: superset
    helm:
      parameters:
        - name: postgresql.enabled
          value: "false"
        - name: redis.enabled
          value: "true"
        - name: supersetNode.connections.db_host
          value: "postgresql"
        - name: supersetNode.connections.db_pass
          value: "password"
        - name: supersetNode.connections.db_user
          value: "postgres"
        - name: supersetNode.connections.db_name
          value: "superset"          
          
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
