apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.1.1
    chart: superset
    helm:
      parameters:
        - name: bootstrapScript
          value: |
            #!/bin/bash
            # Pre-install lib require for oauth and SASL for Spark Thrift Server Connection
            RUN pip install psycopg2==2.8.5 redis==3.2.1 Authlib==0.15.3 
            RUN apt-get update -y
            RUN apt-get install -y libsasl2-modules vim netcat
            # Change SuperSET CSS for the custom oauth icon
            RUN cssfile=$(ls /app/superset/static/assets/theme*.css | head -n1) && echo '.customlogo {width:148px;height:51px;background:url(/static/assets/images/login.png);background-size:148px 51px; }'  >> $cssfile            
        - name:  extraEnvFromSecret
          value: |
            - name: STS_PASS
              valueFrom:
                secretKeyRef:
                  name: data-lake
                  key: sts_admin_password
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: data-lake
                  key: postgresql-password
            - name: CLIENT_ID
        - name: postgresql.enabled
          value: "false"
        - name: redis.enabled
          value: "true"
        - name: supersetNode.connections.db_host
          value: "postgresql"
        - name: supersetNode.connections.db_pass
          value: "password"
        - name: supersetNode.connections.db_user
          value: "postgres"
        - name: supersetNode.connections.db_name
          value: "superset"          
          
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
