apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.3.8
    chart: superset
    helm:
      parameters:
        - name: image.tag
          value: 1.3.0
        - name: bootstrapScript
          value: |
            #!/bin/sh
            # Pre-install lib require for oauth and SASL for Spark Thrift Server Connection
            pip install psycopg2==2.8.5 redis==3.2.1 Authlib==0.15.3 
            apt-get update -y
            apt-get install -y libsasl2-modules vim netcat
            # Change SuperSET CSS for the custom oauth icon
            cssfile=$(ls /app/superset/static/assets/theme*.css | head -n1) && echo '.customlogo {width:148px;height:51px;background:url(/static/assets/images/login.png);background-size:148px 51px; }'  >> \$\cssfile
        - name:  envFromSecrets
          value: data-lake
        - name: postgresql.enabled
          value: "false"
        - name: redis.enabled
          value: "true"
        - name: supersetNode.connections.db_host
          value: "postgresql"
        - name: supersetNode.connections.db_pass
          value: \$\DB_PASS
        - name: supersetNode.connections.db_user
          value: "postgres"
        - name: supersetNode.connections.db_name
          value: "superset"          
          
  project: operation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
