apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testdata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  destination:
    namespace: data-lake
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: v1/benchmarkdata
    repoURL: 'https://github.com/jackiefong/datalake.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
